<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Anu Sharma">
<meta name="dcterms.date" content="2025-10-03">

<title>Assignment 04</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="assignment04-anush09_files/libs/clipboard/clipboard.min.js"></script>
<script src="assignment04-anush09_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="assignment04-anush09_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="assignment04-anush09_files/libs/quarto-html/popper.min.js"></script>
<script src="assignment04-anush09_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="assignment04-anush09_files/libs/quarto-html/anchor.min.js"></script>
<link href="assignment04-anush09_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="assignment04-anush09_files/libs/quarto-html/quarto-syntax-highlighting-c8ad9e5dbd60b7b70b38521ab19b7da4.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="assignment04-anush09_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="assignment04-anush09_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="assignment04-anush09_files/libs/bootstrap/bootstrap-6a6767b7fd3dbe5e3244bc8c12a8bda7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#github-url" id="toc-github-url" class="nav-link active" data-scroll-target="#github-url"><span class="header-section-number">1</span> Github URL</a></li>
  <li><a href="#generative-ai-use-declaration" id="toc-generative-ai-use-declaration" class="nav-link" data-scroll-target="#generative-ai-use-declaration"><span class="header-section-number">2</span> Generative AI Use Declaration</a></li>
  <li><a href="#note-to-instructor" id="toc-note-to-instructor" class="nav-link" data-scroll-target="#note-to-instructor"><span class="header-section-number">3</span> Note to Instructor:</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering"><span class="header-section-number">4</span> Feature Engineering</a></li>
  <li><a href="#generalized-linear-regression-model" id="toc-generalized-linear-regression-model" class="nav-link" data-scroll-target="#generalized-linear-regression-model"><span class="header-section-number">5</span> Generalized Linear Regression model</a></li>
  <li><a href="#polynomial-regression-model" id="toc-polynomial-regression-model" class="nav-link" data-scroll-target="#polynomial-regression-model"><span class="header-section-number">6</span> Polynomial Regression model</a></li>
  <li><a href="#random-forest-regression" id="toc-random-forest-regression" class="nav-link" data-scroll-target="#random-forest-regression"><span class="header-section-number">7</span> Random Forest Regression</a></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison"><span class="header-section-number">8</span> Model Comparison</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 04</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Anu Sharma </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Boston University
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 3, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 8, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="github-url" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="github-url"><span class="header-section-number">1</span> Github URL</h2>
<p>https://github.com/met-ad-688/assignment-04-anush-09.git</p>
</section>
<section id="generative-ai-use-declaration" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="generative-ai-use-declaration"><span class="header-section-number">2</span> Generative AI Use Declaration</h2>
<ol type="1">
<li>Used AI for code cleaning and sorting errors.</li>
<li>Used it for figuring out some plotting issues in the last cell.</li>
</ol>
</section>
<section id="note-to-instructor" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="note-to-instructor"><span class="header-section-number">3</span> Note to Instructor:</h2>
<p>I used Generalized Linear Regression considering Module05 Lab02 Section4.</p>
<div id="695f55f4" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> SparkSession</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.express <span class="im">as</span> px</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.io <span class="im">as</span> pio</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>pio.renderers.default <span class="op">=</span> <span class="st">"notebook+notebook_connected+vscode"</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize Spark Session</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>spark <span class="op">=</span> SparkSession.builder.appName(<span class="st">"LightcastData"</span>).getOrCreate()</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Data</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> spark.read.option(<span class="st">"header"</span>, <span class="st">"true"</span>).option(<span class="st">"inferSchema"</span>, <span class="st">"true"</span>).option(<span class="st">"multiLine"</span>,<span class="st">"true"</span>).option(<span class="st">"escape"</span>, <span class="st">"</span><span class="ch">\"</span><span class="st">"</span>).csv(<span class="st">"./data/lightcast_job_postings.csv"</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># # Show Schema and Sample Data</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---This is Diagnostic check, No need to print it in the final doc---")</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># # df.printSchema() # comment this line when rendering the submission</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># df.show(5)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 61:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
</div>
</section>
<section id="feature-engineering" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="feature-engineering"><span class="header-section-number">4</span> Feature Engineering</h2>
<div id="381bfceb" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> col, <span class="bu">pow</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.feature <span class="im">import</span> StringIndexer, OneHotEncoder, VectorAssembler</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml <span class="im">import</span> Pipeline</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> GeneralizedLinearRegression</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop missing values</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>key_features <span class="op">=</span> [</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"DURATION"</span>, <span class="st">"SALARY_FROM"</span>, <span class="st">"SALARY_TO"</span>, <span class="st">"MIN_YEARS_EXPERIENCE"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"EMPLOYMENT_TYPE_NAME"</span>, <span class="st">"STATE_NAME"</span>, <span class="st">"SALARY"</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>df_clean <span class="op">=</span> df.dropna(subset<span class="op">=</span>key_features)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Categorical transformations</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>cat_cols <span class="op">=</span> [<span class="st">"EMPLOYMENT_TYPE_NAME"</span>, <span class="st">"STATE_NAME"</span>]</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>indexers <span class="op">=</span> [StringIndexer(inputCol<span class="op">=</span>c, outputCol<span class="op">=</span>c<span class="op">+</span><span class="st">"_IDX"</span>, handleInvalid<span class="op">=</span><span class="st">"keep"</span>) <span class="cf">for</span> c <span class="kw">in</span> cat_cols]</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>encoders <span class="op">=</span> [OneHotEncoder(inputCol<span class="op">=</span>c<span class="op">+</span><span class="st">"_IDX"</span>, outputCol<span class="op">=</span>c<span class="op">+</span><span class="st">"_OHE"</span>, dropLast<span class="op">=</span><span class="va">True</span>) <span class="cf">for</span> c <span class="kw">in</span> cat_cols]</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co">#  Assemble features</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>cont_cols <span class="op">=</span> [<span class="st">"DURATION"</span>, <span class="st">"SALARY_FROM"</span>, <span class="st">"SALARY_TO"</span>, <span class="st">"MIN_YEARS_EXPERIENCE"</span>]</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>assembler_inputs <span class="op">=</span> cont_cols <span class="op">+</span> [c<span class="op">+</span><span class="st">"_OHE"</span> <span class="cf">for</span> c <span class="kw">in</span> cat_cols]</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>assembler <span class="op">=</span> VectorAssembler(</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    inputCols<span class="op">=</span>assembler_inputs,</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">"features"</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>pipeline <span class="op">=</span> Pipeline(stages<span class="op">=</span>indexers <span class="op">+</span> encoders <span class="op">+</span> [assembler])</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>df_transformed <span class="op">=</span> pipeline.fit(df_clean).transform(df_clean)</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Train-test split (80/20)</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>train_df, test_df <span class="op">=</span> df_transformed.randomSplit([<span class="fl">0.8</span>, <span class="fl">0.2</span>], seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="co"># 80% for training and 20% for testing to ensure enough data for model training and validation.</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Create polynomial feature ( by squaring MIN_YEARS_EXPERIENCE)</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>df_poly <span class="op">=</span> df_transformed.withColumn(</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">"MIN_YEARS_EXPERIENCE_SQ"</span>, <span class="bu">pow</span>(col(<span class="st">"MIN_YEARS_EXPERIENCE"</span>), <span class="dv">2</span>)</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Assemble polynomial features into new vector</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>poly_assembler <span class="op">=</span> VectorAssembler(</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>    inputCols<span class="op">=</span>[<span class="st">"features"</span>, <span class="st">"MIN_YEARS_EXPERIENCE_SQ"</span>],</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">"features_poly"</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>df_final <span class="op">=</span> poly_assembler.transform(df_poly)</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>df_final.show(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 62:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 65:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+--------------------+-----------------+----------------------+----------+--------+---------+--------+-------------------+--------------------+--------------------+-----------+-------------------+--------------------+--------------------+---------------+----------------+--------+------------+-----------+-------------------+----------------+---------------------+-------------+-------------------+-------------+------------------+---------------+--------------------+--------------------+--------------------+-------------+------+-----------+----------------+-------------------+---------+-----------+--------------------+--------------------+------------------+------+--------------------+-----+--------------------+-----+----------+---------------+--------------------+---------------+--------------------+------------+--------------------+------------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------------------+--------------+-------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+-----------------+--------------------+---------------+--------------------+------------+--------------------+----------+--------------------+----------+--------------------+----------+---------------+----------+---------------+---------------+--------------------+--------------+--------------------+--------------------------+-------------------------------+--------------------+-------------------------+-----------------------------+----------------------------------+-----------------+----------------------+-----------------------+----------------------------+------------------+-----------------------+-------+--------------------+-------+--------------------+-------+---------------+-------+---------------+-----------------+----------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------------------+--------------+------------------------+---------------+--------------------+-----------------------+--------------------+
|                  ID|LAST_UPDATED_DATE|LAST_UPDATED_TIMESTAMP|DUPLICATES|  POSTED|  EXPIRED|DURATION|       SOURCE_TYPES|             SOURCES|                 URL|ACTIVE_URLS|ACTIVE_SOURCES_INFO|           TITLE_RAW|                BODY|MODELED_EXPIRED|MODELED_DURATION| COMPANY|COMPANY_NAME|COMPANY_RAW|COMPANY_IS_STAFFING|EDUCATION_LEVELS|EDUCATION_LEVELS_NAME|MIN_EDULEVELS| MIN_EDULEVELS_NAME|MAX_EDULEVELS|MAX_EDULEVELS_NAME|EMPLOYMENT_TYPE|EMPLOYMENT_TYPE_NAME|MIN_YEARS_EXPERIENCE|MAX_YEARS_EXPERIENCE|IS_INTERNSHIP|SALARY|REMOTE_TYPE|REMOTE_TYPE_NAME|ORIGINAL_PAY_PERIOD|SALARY_TO|SALARY_FROM|            LOCATION|                CITY|         CITY_NAME|COUNTY|         COUNTY_NAME|  MSA|            MSA_NAME|STATE|STATE_NAME|COUNTY_OUTGOING|COUNTY_NAME_OUTGOING|COUNTY_INCOMING|COUNTY_NAME_INCOMING|MSA_OUTGOING|   MSA_NAME_OUTGOING|MSA_INCOMING|   MSA_NAME_INCOMING|NAICS2|         NAICS2_NAME|NAICS3|         NAICS3_NAME|NAICS4|         NAICS4_NAME|NAICS5|         NAICS5_NAME|NAICS6|         NAICS6_NAME|             TITLE|          TITLE_NAME|         TITLE_CLEAN|              SKILLS|         SKILLS_NAME|  SPECIALIZED_SKILLS|SPECIALIZED_SKILLS_NAME|CERTIFICATIONS|CERTIFICATIONS_NAME|       COMMON_SKILLS|  COMMON_SKILLS_NAME|     SOFTWARE_SKILLS|SOFTWARE_SKILLS_NAME|      ONET|           ONET_NAME| ONET_2019|      ONET_2019_NAME|             CIP6|           CIP6_NAME|           CIP4|           CIP4_NAME|        CIP2|           CIP2_NAME|SOC_2021_2|     SOC_2021_2_NAME|SOC_2021_3|     SOC_2021_3_NAME|SOC_2021_4|SOC_2021_4_NAME|SOC_2021_5|SOC_2021_5_NAME|LOT_CAREER_AREA|LOT_CAREER_AREA_NAME|LOT_OCCUPATION| LOT_OCCUPATION_NAME|LOT_SPECIALIZED_OCCUPATION|LOT_SPECIALIZED_OCCUPATION_NAME|LOT_OCCUPATION_GROUP|LOT_OCCUPATION_GROUP_NAME|LOT_V6_SPECIALIZED_OCCUPATION|LOT_V6_SPECIALIZED_OCCUPATION_NAME|LOT_V6_OCCUPATION|LOT_V6_OCCUPATION_NAME|LOT_V6_OCCUPATION_GROUP|LOT_V6_OCCUPATION_GROUP_NAME|LOT_V6_CAREER_AREA|LOT_V6_CAREER_AREA_NAME|  SOC_2|          SOC_2_NAME|  SOC_3|          SOC_3_NAME|  SOC_4|     SOC_4_NAME|  SOC_5|     SOC_5_NAME|LIGHTCAST_SECTORS|LIGHTCAST_SECTORS_NAME|NAICS_2022_2|   NAICS_2022_2_NAME|NAICS_2022_3|   NAICS_2022_3_NAME|NAICS_2022_4|   NAICS_2022_4_NAME|NAICS_2022_5|   NAICS_2022_5_NAME|NAICS_2022_6|   NAICS_2022_6_NAME|EMPLOYMENT_TYPE_NAME_IDX|STATE_NAME_IDX|EMPLOYMENT_TYPE_NAME_OHE| STATE_NAME_OHE|            features|MIN_YEARS_EXPERIENCE_SQ|       features_poly|
+--------------------+-----------------+----------------------+----------+--------+---------+--------+-------------------+--------------------+--------------------+-----------+-------------------+--------------------+--------------------+---------------+----------------+--------+------------+-----------+-------------------+----------------+---------------------+-------------+-------------------+-------------+------------------+---------------+--------------------+--------------------+--------------------+-------------+------+-----------+----------------+-------------------+---------+-----------+--------------------+--------------------+------------------+------+--------------------+-----+--------------------+-----+----------+---------------+--------------------+---------------+--------------------+------------+--------------------+------------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------------------+--------------+-------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+-----------------+--------------------+---------------+--------------------+------------+--------------------+----------+--------------------+----------+--------------------+----------+---------------+----------+---------------+---------------+--------------------+--------------+--------------------+--------------------------+-------------------------------+--------------------+-------------------------+-----------------------------+----------------------------------+-----------------+----------------------+-----------------------+----------------------------+------------------+-----------------------+-------+--------------------+-------+--------------------+-------+---------------+-------+---------------+-----------------+----------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------------------+--------------+------------------------+---------------+--------------------+-----------------------+--------------------+
|57b527ea0f91db5bb...|         9/6/2024|  2024-09-06 20:32:...|         0|6/2/2024|7/27/2024|      55|[\n  "Job Board"\n]|[\n  "simplyhired...|[\n  "https://www...|         []|               NULL|Power, Utilities ...|Power, Utilities ...|      7/27/2024|              55| 5732448|    Deloitte|   Deloitte|              false| [\n  2,\n  3\n]| [\n  "Bachelor's ...|            2|  Bachelor's degree|            3|   Master's degree|              1|Full-time (&gt; 32 h...|                   6|                NULL|        false|192800|          0|          [None]|               year|   241000|     144600|{\n  "lat": 42.33...|    RGV0cm9pdCwgTUk=|       Detroit, MI| 26163|           Wayne, MI|19820|Detroit-Warren-De...|   26|  Michigan|          26163|           Wayne, MI|          26163|           Wayne, MI|       19820|Detroit-Warren-De...|       19820|Detroit-Warren-De...|    54|Professional, Sci...|   541|Professional, Sci...|  5416|Management, Scien...| 54161|Management Consul...|541611|Administrative Ma...|ET8AEDEB1F4C3091D3|Management Consul...|power utilities r...|[\n  "KS122VL71WF...|[\n  "Design Spec...|[\n  "KS122VL71WF...|   [\n  "Design Spec...|            []|                 []|[\n  "KS1218W78FG...|[\n  "Management"...|[\n  "KS1219W70LY...|[\n  "C++ (Progra...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|[\n  "45.0702"\n]|[\n  "Geographic ...|[\n  "45.07"\n]|[\n  "Geography a...|[\n  "45"\n]|[\n  "Social Scie...|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231010|Business Intellig...|                  23101011|           General ERP Analy...|                2310|     Business Intellig...|                     23101011|              General ERP Analy...|           231010|  Business Intellig...|                   2310|        Business Intellig...|                23|   Information Techn...|15-0000|Computer and Math...|15-2000|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|        [\n  3\n]|  [\n  "Green Jobs:...|          54|Professional, Sci...|         541|Professional, Sci...|        5416|Management, Scien...|       54161|Management Consul...|      541611|Administrative Ma...|                     0.0|           8.0|           (3,[0],[1.0])| (51,[8],[1.0])|(58,[0,1,2,3,4,15...|                   36.0|(59,[0,1,2,3,4,15...|
|dd191e2ce3062c371...|         9/6/2024|  2024-09-06 20:32:...|         0|6/2/2024|6/20/2024|      18|[\n  "Job Board"\n]|[\n  "phoenixrecr...|[\n  "https://www...|         []|               NULL| SAP FSCM Consultant|Job Description: ...|      6/20/2024|              18| 8592955|   Accenture|  Accenture|              false| [\n  1,\n  2\n]| [\n  "Associate d...|            1|   Associate degree|            2| Bachelor's degree|              1|Full-time (&gt; 32 h...|                  12|                NULL|        false|125900|          0|          [None]|               year|   188600|      63200|{\n  "lat": 0,\n ...|W1Vua25vd24gQ2l0e...|[Unknown City], AZ|  4999|[Unknown county], AZ| NULL|                NULL|    4|   Arizona|           4999|[Unknown county], AZ|           4999|[Unknown county], AZ|        NULL|                NULL|        NULL|                NULL|    54|Professional, Sci...|   541|Professional, Sci...|  5415|Computer Systems ...| 54151|Computer Systems ...|541512|Computer Systems ...|ETF594A2C05D212506|Peoplesoft FSCM C...| sap fscm consultant|[\n  "KS7G7VL78R2...|[\n  "Profit Cent...|[\n  "KS7G7VL78R2...|   [\n  "Profit Cent...|            []|                 []|[\n  "KS122ZF75YV...|[\n  "Digitizatio...|[\n  "KS7G7VL78R2...|[\n  "Profit Cent...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|               []|                  []|             []|                  []|          []|                  []|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231010|Business Intellig...|                  23101011|           General ERP Analy...|                2310|     Business Intellig...|                     23101011|              General ERP Analy...|           231010|  Business Intellig...|                   2310|        Business Intellig...|                23|   Information Techn...|15-0000|Computer and Math...|15-2000|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|             NULL|                  NULL|          54|Professional, Sci...|         541|Professional, Sci...|        5415|Computer Systems ...|       54151|Computer Systems ...|      541512|Computer Systems ...|                     0.0|          11.0|           (3,[0],[1.0])|(51,[11],[1.0])|(58,[0,1,2,3,4,18...|                  144.0|(59,[0,1,2,3,4,18...|
|146621e071735303b...|        7/12/2024|  2024-07-13 03:22:...|         0|6/2/2024|6/22/2024|      20|  [\n  "Company"\n]|  [\n  "jobs.net"\n]|[\n  "https://bcf...|         []|               NULL|      DATA ANALYTICS|Data Modeler Mode...|      6/22/2024|              20|99484525|   BCforward|  BCforward|               true|      [\n  99\n]| [\n  "No Educatio...|           99|No Education Listed|         NULL|              NULL|              1|Full-time (&gt; 32 h...|                   5|                NULL|        false|118560|          1|          Remote|               hour|   120328|     116792|{\n  "lat": 39.76...|SW5kaWFuYXBvbGlzL...|  Indianapolis, IN| 18097|          Marion, IN|26900|Indianapolis-Carm...|   18|   Indiana|          18097|          Marion, IN|          18097|          Marion, IN|       26900|Indianapolis-Carm...|       26900|Indianapolis-Carm...|    54|Professional, Sci...|   541|Professional, Sci...|  5416|Management, Scien...| 54161|Management Consul...|541611|Administrative Ma...|ET0000000000000000|        Unclassified|      data analytics|[\n  "KSOH5A22ONU...|[\n  "Databricks"...|[\n  "KSOH5A22ONU...|   [\n  "Databricks"...|            []|                 []|[\n  "KS1203C6N9B...|[\n  "Research",\...|[\n  "KSOH5A22ONU...|[\n  "Databricks"...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|               []|                  []|             []|                  []|          []|                  []|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231113|Data / Data Minin...|                  23111310|                   Data Analyst|                2311|     Data Analysis and...|                     23111310|                      Data Analyst|           231113|  Data / Data Minin...|                   2311|        Data Analysis and...|                23|   Information Techn...|15-0000|Computer and Math...|15-2000|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|        [\n  7\n]|  [\n  "Artificial ...|          54|Professional, Sci...|         541|Professional, Sci...|        5416|Management, Scien...|       54161|Management Consul...|      541611|Administrative Ma...|                     0.0|          21.0|           (3,[0],[1.0])|(51,[21],[1.0])|(58,[0,1,2,3,4,28...|                   25.0|(59,[0,1,2,3,4,28...|
|799924ec2f2bf4f2e...|         9/6/2024|  2024-09-06 20:32:...|         0|6/2/2024|7/27/2024|      55|[\n  "Job Board"\n]|[\n  "simplyhired...|[\n  "https://www...|         []|               NULL|Power, Utilities ...|Power, Utilities ...|      7/27/2024|              55| 5732448|    Deloitte|   Deloitte|              false| [\n  2,\n  3\n]| [\n  "Bachelor's ...|            2|  Bachelor's degree|            3|   Master's degree|              1|Full-time (&gt; 32 h...|                   6|                NULL|        false|192800|          0|          [None]|               year|   241000|     144600|{\n  "lat": 39.10...|Q2luY2lubmF0aSwgT0g=|    Cincinnati, OH| 39061|        Hamilton, OH|17140|Cincinnati, OH-KY-IN|   39|      Ohio|          39061|        Hamilton, OH|          39061|        Hamilton, OH|       17140|Cincinnati, OH-KY-IN|       17140|Cincinnati, OH-KY-IN|    54|Professional, Sci...|   541|Professional, Sci...|  5416|Management, Scien...| 54161|Management Consul...|541611|Administrative Ma...|ET8AEDEB1F4C3091D3|Management Consul...|power utilities r...|[\n  "KS122VL71WF...|[\n  "Design Spec...|[\n  "KS122VL71WF...|   [\n  "Design Spec...|            []|                 []|[\n  "KS1218W78FG...|[\n  "Management"...|[\n  "KS1219W70LY...|[\n  "C++ (Progra...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|[\n  "45.0702"\n]|[\n  "Geographic ...|[\n  "45.07"\n]|[\n  "Geography a...|[\n  "45"\n]|[\n  "Social Scie...|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231010|Business Intellig...|                  23101011|           General ERP Analy...|                2310|     Business Intellig...|                     23101011|              General ERP Analy...|           231010|  Business Intellig...|                   2310|        Business Intellig...|                23|   Information Techn...|15-0000|Computer and Math...|15-2000|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|        [\n  3\n]|  [\n  "Green Jobs:...|          54|Professional, Sci...|         541|Professional, Sci...|        5416|Management, Scien...|       54161|Management Consul...|      541611|Administrative Ma...|                     0.0|           7.0|           (3,[0],[1.0])| (51,[7],[1.0])|(58,[0,1,2,3,4,14...|                   36.0|(59,[0,1,2,3,4,14...|
|6396d0f5e8c9feaa0...|         9/6/2024|  2024-09-06 20:32:...|         0|6/2/2024|6/18/2024|      16|[\n  "Job Board"\n]|[\n  "phoenixrecr...|[\n  "https://www...|         []|               NULL|  SAP BTP Consultant|Job Description: ...|      6/18/2024|              16| 8592955|   Accenture|  Accenture|              false| [\n  1,\n  2\n]| [\n  "Associate d...|            1|   Associate degree|            2| Bachelor's degree|              1|Full-time (&gt; 32 h...|                  12|                NULL|        false|116500|          0|          [None]|               year|   169800|      63200|{\n  "lat": 0,\n ...|W1Vua25vd24gQ2l0e...|[Unknown City], AZ|  4999|[Unknown county], AZ| NULL|                NULL|    4|   Arizona|           4999|[Unknown county], AZ|           4999|[Unknown county], AZ|        NULL|                NULL|        NULL|                NULL|    54|Professional, Sci...|   541|Professional, Sci...|  5415|Computer Systems ...| 54151|Computer Systems ...|541512|Computer Systems ...|ETCBD54F6B90888F99|     SAP Consultants|  sap btp consultant|[\n  "KS122ZF75YV...|[\n  "Digitizatio...|[\n  "ES43DB1E2DE...|   [\n  "Cloud Servi...|            []|                 []|[\n  "KS122ZF75YV...|[\n  "Digitizatio...|[\n  "KS1267G65F6...|[\n  "Apache Mave...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|               []|                  []|             []|                  []|          []|                  []|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231010|Business Intellig...|                  23101011|           General ERP Analy...|                2310|     Business Intellig...|                     23101011|              General ERP Analy...|           231010|  Business Intellig...|                   2310|        Business Intellig...|                23|   Information Techn...|15-0000|Computer and Math...|15-2000|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|             NULL|                  NULL|          54|Professional, Sci...|         541|Professional, Sci...|        5415|Computer Systems ...|       54151|Computer Systems ...|      541512|Computer Systems ...|                     0.0|          11.0|           (3,[0],[1.0])|(51,[11],[1.0])|(58,[0,1,2,3,4,18...|                  144.0|(59,[0,1,2,3,4,18...|
+--------------------+-----------------+----------------------+----------+--------+---------+--------+-------------------+--------------------+--------------------+-----------+-------------------+--------------------+--------------------+---------------+----------------+--------+------------+-----------+-------------------+----------------+---------------------+-------------+-------------------+-------------+------------------+---------------+--------------------+--------------------+--------------------+-------------+------+-----------+----------------+-------------------+---------+-----------+--------------------+--------------------+------------------+------+--------------------+-----+--------------------+-----+----------+---------------+--------------------+---------------+--------------------+------------+--------------------+------------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------------------+--------------+-------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+-----------------+--------------------+---------------+--------------------+------------+--------------------+----------+--------------------+----------+--------------------+----------+---------------+----------+---------------+---------------+--------------------+--------------+--------------------+--------------------------+-------------------------------+--------------------+-------------------------+-----------------------------+----------------------------------+-----------------+----------------------+-----------------------+----------------------------+------------------+-----------------------+-------+--------------------+-------+--------------------+-------+---------------+-------+---------------+-----------------+----------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------------------+--------------+------------------------+---------------+--------------------+-----------------------+--------------------+
only showing top 5 rows
</code></pre>
</div>
</div>
</section>
<section id="generalized-linear-regression-model" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="generalized-linear-regression-model"><span class="header-section-number">5</span> Generalized Linear Regression model</h2>
<div id="8a96d4c9" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> GeneralizedLinearRegression(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    family<span class="op">=</span><span class="st">"gaussian"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    link<span class="op">=</span><span class="st">"identity"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    featuresCol<span class="op">=</span><span class="st">"features"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">"SALARY"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    maxIter<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    regParam<span class="op">=</span><span class="fl">0.3</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>lr_model <span class="op">=</span> lr.fit(train_df)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> RegressionEvaluator</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>lr_predictions <span class="op">=</span> lr_model.transform(test_df)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>evaluator <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Coefficients:"</span>, lr_model.coefficients)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Intercept:"</span>, lr_model.intercept)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"R²:"</span>, evaluator.setMetricName(<span class="st">"r2"</span>).evaluate(lr_predictions))</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"RMSE:"</span>, evaluator.setMetricName(<span class="st">"rmse"</span>).evaluate(lr_predictions))</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MAE:"</span>, evaluator.setMetricName(<span class="st">"mae"</span>).evaluate(lr_predictions))</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficient statistics</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>training_summary <span class="op">=</span> lr_model.summary</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    coefs <span class="op">=</span> lr_model.coefficients.toArray().tolist()</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    se <span class="op">=</span> training_summary.coefficientStandardErrors</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    tvals <span class="op">=</span> training_summary.tValues</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    pvals <span class="op">=</span> training_summary.pValues</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>    coef_df <span class="op">=</span> spark.createDataFrame(</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>        [</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>            (<span class="bu">float</span>(coefs[i]), <span class="bu">float</span>(se[i]), <span class="bu">float</span>(tvals[i]), <span class="bu">float</span>(pvals[i]),</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>             <span class="bu">float</span>(coefs[i] <span class="op">-</span> <span class="fl">1.96</span><span class="op">*</span>se[i]), <span class="bu">float</span>(coefs[i] <span class="op">+</span> <span class="fl">1.96</span><span class="op">*</span>se[i]))</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(coefs))</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>        [<span class="st">"Coefficient"</span>, <span class="st">"StdError"</span>, <span class="st">"tValue"</span>, <span class="st">"pValue"</span>, <span class="st">"CI_lower"</span>, <span class="st">"CI_upper"</span>]</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>    coef_df.show(truncate<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Actualy not needed for GLR but I added it when I was previously using LR.</span></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Coefficient statistics not available (L-BGFS fallback):"</span>, <span class="bu">str</span>(e))</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a><span class="co"># df_final.printSchema()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 69:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Coefficients: [0.10577257338987292,0.4897760646675632,0.5031355811149286,5.821447063989891,-63.13234211764908,-37.24918495447914,240.2496005871974,48.31465068112287,152.96207700756838,-176.77153212602502,85.33910314560474,434.28702577440487,-161.42079058360767,-15.678039153034717,-118.88023960359375,-161.45114829498186,-102.29690138402427,202.46320733110622,-141.30430068749794,-10.336921084699812,46.18232664748482,-139.7522513504501,-91.77765784576877,756.3227801189014,88.81214010053442,-194.06691355630176,92.42948084492659,-238.66548174672735,-232.9013492626481,49.64728458137663,-169.13719812248235,-145.48484292668024,-121.95157094464349,-99.6819901995056,-159.90690621771986,-201.88892491962216,-187.93226914248663,-97.41512683302918,-200.87692671645,-193.2008460392148,-224.35294989361188,50.530082652301964,42.19504489586543,-80.67373549847771,-132.2894187558734,-134.85646865840482,-191.28731365448144,-161.90766503071904,147.48514217917366,344.69364885521287,172.6083494391896,-142.18206008275982,-192.08893673890222,-86.81171897251811,-139.9320627067798,-118.84967713486162,374.329274291932,-226.00705073681388]
Intercept: 771.471741322882</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 70:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>R²: 0.9991007618414153</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 71:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>RMSE: 1269.8322518177556</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 72:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>MAE: 439.38359836620407</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 73:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+-------------------+---------------------+----------------------+-------------------+-------------------+------------------+
|Coefficient        |StdError             |tValue                |pValue             |CI_lower           |CI_upper          |
+-------------------+---------------------+----------------------+-------------------+-------------------+------------------+
|0.10577257338987292|0.8210812224588767   |0.12882108431747807   |0.8975014656141185 |-1.5035466226295255|1.7150917694092713|
|0.4897760646675632 |4.7249581342235624E-4|1036.5722843553756    |0.0                |0.4888499728732554 |0.490702156461871 |
|0.5031355811149286 |3.462378911127178E-4 |1453.149970091323     |0.0                |0.5024569548483477 |0.5038142073815095|
|5.821447063989891  |4.284466788662476    |1.358733151904587     |0.17425770783310224|-2.576107841788562 |14.219001969768343|
|-63.13234211764908 |15760.586188378582   |-0.004005710280256017 |0.9968039833938374 |-30953.88127133967 |30827.61658710437 |
|-37.24918495447914 |15760.644925545      |-0.0023634302486001263|0.9981142982265387 |-30928.113239022678|30853.61486911372 |
|240.2496005871974  |15760.786548337737   |0.015243503225575763  |0.9878381785111885 |-30650.892034154767|31131.391235329163|
|48.31465068112287  |4500.489171196371    |0.010735422049305658  |0.9914347225454412 |-8772.644124863764 |8869.27342622601  |
|152.96207700756838 |4500.527913588752    |0.03398758544430299   |0.9728876379345217 |-8668.072633626385 |8973.996787641523 |
|-176.77153212602502|4500.662388715528    |-0.03927678125096491  |0.9686703973498092 |-8998.06981400846  |8644.52674975641  |
|85.33910314560474  |4500.661123424321    |0.01896145939569754   |0.9848721785122763 |-8735.956698766064 |8906.634905057273 |
|434.28702577440487 |4500.712114327836    |0.09649295816807957   |0.923130741260461  |-8387.108718308154 |9255.682769856965 |
|-161.42079058360767|4500.800288897419    |-0.035864908510115576 |0.9713906968532522 |-8982.989356822549 |8660.147775655332 |
|-15.678039153034717|4500.846381301049    |-0.003483353535052823 |0.9972207517613536 |-8837.336946503092 |8805.98086819702  |
|-118.88023960359375|4500.835491139143    |-0.026412927074903073 |0.9789284399252751 |-8940.517802236314 |8702.757323029127 |
|-161.45114829498186|4500.876955298087    |-0.03587104244316965  |0.9713858059543845 |-8983.169980679231 |8660.267684089267 |
|-102.29690138402427|4500.890163796606    |-0.022728148801954864 |0.9818675149292697 |-8924.041622425373 |8719.447819657324 |
|202.46320733110622 |4500.914400805749    |0.04498268336204338   |0.964121889624981  |-8619.329018248163 |9024.255432910375 |
|-141.30430068749794|4500.940965632624    |-0.03139439103210657  |0.974955556934114  |-8963.148593327442 |8680.539991952446 |
|-10.336921084699812|4500.925771743812    |-0.002296621097284823 |0.9981676026572368 |-8832.151433702571 |8811.477591533172 |
+-------------------+---------------------+----------------------+-------------------+-------------------+------------------+
only showing top 20 rows
</code></pre>
</div>
</div>
<section id="inference" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="inference"><span class="header-section-number">5.1</span> Inference</h3>
<p>The Generalized Linear Regression model gave very high accuracy (R² ≈ 0.9991), explaining almost all variation in salaries. Prediction errors were very small (RMSE ≈ 1269, MAE ≈ 439). As expected, more years of experience are linked with higher pay, and job type and location also matter. Looking at coefficients, some predictors (like the second and third features) are highly significant with very low p‑values, while many others have large standard errors and are not statistically meaningful. This shows the presence of multicollinearity: several features are strongly correlated, so the model predicts well overall but individual coefficient estimates are unstable.</p>
</section>
</section>
<section id="polynomial-regression-model" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="polynomial-regression-model"><span class="header-section-number">6</span> Polynomial Regression model</h2>
<div id="007d448a" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> GeneralizedLinearRegression</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># train/test</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>train_poly, test_poly <span class="op">=</span> df_final.randomSplit([<span class="fl">0.8</span>, <span class="fl">0.2</span>], seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Regression model using polynomial features</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>lr_poly <span class="op">=</span> GeneralizedLinearRegression(</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    family<span class="op">=</span><span class="st">"gaussian"</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    link<span class="op">=</span><span class="st">"identity"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    featuresCol<span class="op">=</span><span class="st">"features_poly"</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">"SALARY"</span>,</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    maxIter<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    regParam<span class="op">=</span><span class="fl">0.3</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="co">#  Fit model on training data</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>lr_poly_model <span class="op">=</span> lr_poly.fit(train_poly)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> RegressionEvaluator</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>poly_predictions <span class="op">=</span> lr_poly_model.transform(test_poly)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>evaluator <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>)</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Polynomial Regression Results"</span>)</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Coefficients:"</span>, lr_poly_model.coefficients)</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Intercept:"</span>, lr_poly_model.intercept)</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"R²:"</span>, evaluator.setMetricName(<span class="st">"r2"</span>).evaluate(poly_predictions))</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"RMSE:"</span>, evaluator.setMetricName(<span class="st">"rmse"</span>).evaluate(poly_predictions))</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MAE:"</span>, evaluator.setMetricName(<span class="st">"mae"</span>).evaluate(poly_predictions))</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficient statistics</span></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>poly_summary <span class="op">=</span> lr_poly_model.summary</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>    coefs <span class="op">=</span> lr_poly_model.coefficients.toArray().tolist()</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>    se <span class="op">=</span> poly_summary.coefficientStandardErrors</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>    tvals <span class="op">=</span> poly_summary.tValues</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>    pvals <span class="op">=</span> poly_summary.pValues</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>    coef_poly_df <span class="op">=</span> spark.createDataFrame(</span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>        [</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>            (<span class="bu">float</span>(coefs[i]), <span class="bu">float</span>(se[i]), <span class="bu">float</span>(tvals[i]), <span class="bu">float</span>(pvals[i]),</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>             <span class="bu">float</span>(coefs[i] <span class="op">-</span> <span class="fl">1.96</span><span class="op">*</span>se[i]), <span class="bu">float</span>(coefs[i] <span class="op">+</span> <span class="fl">1.96</span><span class="op">*</span>se[i]))</span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(coefs))</span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>        [<span class="st">"Coefficient"</span>, <span class="st">"StdError"</span>, <span class="st">"tValue"</span>, <span class="st">"pValue"</span>, <span class="st">"CI_lower"</span>, <span class="st">"CI_upper"</span>]</span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>    coef_poly_df.show(truncate<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Actualy not needed for GLR but I added it when I was previously using LR.</span></span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Coefficient statistics not available (L-BGFS fallback):"</span>, <span class="bu">str</span>(e))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 77:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Polynomial Regression Results
Coefficients: [0.10864189686946173,0.4898446498795814,0.5031330094998685,-7.294074629446415,-61.606183030030984,-36.42477835447172,234.5785726337609,47.66495235497268,153.30872148381684,-176.2483283327536,83.9420652739141,434.07175893403144,-161.97789924707783,-15.370297973052363,-119.3787727802767,-161.94452829454534,-102.0712038173867,201.45561915371567,-140.2180176255666,-9.181294490038646,45.46520302014749,-139.59475217986548,-90.96205773513772,755.7997862985653,91.25321470444824,-192.37388895594734,92.06768904691285,-238.82762343754223,-232.79724289167783,46.988988491411725,-168.5208658938645,-145.86104897935874,-122.65183729247258,-97.95064001860672,-155.79027411246554,-202.70247726846625,-187.7309421134543,-98.09748718742412,-200.76815604456365,-192.61329916789478,-224.5383725545915,52.618094862437424,43.978613627274086,-81.22525014807809,-131.6257250593234,-134.83735400335175,-191.49970597043983,-162.87607913749576,146.14802544190084,341.3370623433174,171.74420670609214,-142.83066925953963,-195.21965382722956,-85.13674407585455,-139.27991520093798,-118.77551011346809,376.6718850326892,-225.64627278434565,0.9616178547957062]
Intercept: 795.9342167087742</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 78:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>R²: 0.9991016319916092</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 79:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>RMSE: 1269.2177248430587</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 80:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>MAE: 438.815563380054</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 81:&gt;                                                         (0 + 1) / 1]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+-------------------+---------------------+----------------------+------------------+-------------------+-------------------+
|Coefficient        |StdError             |tValue                |pValue            |CI_lower           |CI_upper           |
+-------------------+---------------------+----------------------+------------------+-------------------+-------------------+
|0.10864189686946173|0.8210834577114463   |0.13231529127656813   |0.8947372190517244|-1.500681680244973 |1.7179654739838965 |
|0.4898446498795814 |4.7714484248743565E-4|1026.6162520502987    |0.0               |0.488909445988306  |0.49077985377085676|
|0.5031330094998685 |3.4624581479118603E-4|1453.1092882763016    |0.0               |0.5024543677028778 |0.5038116512968592 |
|-7.294074629446415 |13.410941333060745   |-0.543889832063094    |0.5865277899146577|-33.57951964224547 |18.991370383352645 |
|-61.606183030030984|15760.538813755664   |-0.0039088881261002085|0.996881234114777 |-30952.262257991133|30829.04989193107  |
|-36.42477835447172 |15760.597501615233   |-0.0023111292798854047|0.9981560271332635|-30927.19588152033 |30854.346324811388 |
|234.5785726337609  |15760.740061617484   |0.0148837282841201    |0.9881251986163893|-30656.471948136506|31125.629093404026 |
|47.66495235497268  |4500.475667629807    |0.010591092114508779  |0.9915498721391205|-8773.267356199447 |8868.597260909393  |
|153.30872148381684 |4500.51437841101     |0.03406471096264897   |0.9728261376737084|-8667.699460201762 |8974.316903169394  |
|-176.2483283327536 |4500.648869151094    |-0.03916064848800287  |0.9687629846908643|-8997.520111868896 |8645.02345520339   |
|83.9420652739141   |4500.647778877783    |0.018651107440103808  |0.9851197544098045|-8737.32758132654  |8905.211711874368  |
|434.07175893403144 |4500.6985708954635   |0.09644541888253318   |0.9231684953558019|-8387.297440021077 |9255.44095788914   |
|-161.97789924707783|4500.786772737273    |-0.03598879649847679  |0.9712919145273127|-8983.519973812134 |8659.564175317977  |
|-15.370297973052363|4500.832842508601    |-0.0034149897387625522|0.9972752967985401|-8837.00266928991  |8806.262073343807  |
|-119.3787727802767 |4500.821968423608    |-0.026523771350611444 |0.978840031946246 |-8940.989830890549 |8702.232285329994  |
|-161.94452829454534|4500.863431924387    |-0.03598076918883637  |0.9712983151072367|-8983.636854866345 |8659.747798277254  |
|-102.0712038173867 |4500.876620307754    |-0.0226780719464395   |0.9819074593485553|-8923.789379620584 |8719.646971985812  |
|201.45561915371567 |4500.900957815064    |0.04475895404983786   |0.9643002163572982|-8620.31025816381  |9023.221496471242  |
|-140.2180176255666 |4500.927539746499    |-0.031153138189259532 |0.9751479506306358|-8962.035995528704 |8681.599960277572  |
|-9.181294490038646 |4500.9123621176905   |-0.0020398740858217517|0.9983724523724109|-8830.969524240712 |8812.606935260634  |
+-------------------+---------------------+----------------------+------------------+-------------------+-------------------+
only showing top 20 rows
</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
</div>
<section id="inference-1" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="inference-1"><span class="header-section-number">6.1</span> Inference</h3>
<p>The Polynomial Regression model also achieved very high accuracy (R² ≈ 0.9991), explaining nearly all variation in salaries. Errors were very small (RMSE ≈ 1269, MAE ≈ 439), almost the same as the linear model. The results again confirm that experience, job type, and location strongly influence pay. Looking at coefficients, a few predictors (like the second and third features) are highly significant with very low p‑values, but many others show very large standard errors and are not statistically reliable. This again points to multicollinearity: several features overlap in information, so while the model predicts salaries very well, the individual coefficient estimates remain unstable</p>
</section>
</section>
<section id="random-forest-regression" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="random-forest-regression"><span class="header-section-number">7</span> Random Forest Regression</h2>
<div id="136884e7" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> RandomForestRegressor</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> RegressionEvaluator</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Train-test split</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>train_rf, test_rf <span class="op">=</span> df_transformed.randomSplit([<span class="fl">0.8</span>, <span class="fl">0.2</span>], seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Random Forest Regression</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>rf <span class="op">=</span> RandomForestRegressor(</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    featuresCol<span class="op">=</span><span class="st">"features"</span>,</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">"SALARY"</span>,</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>    numTrees<span class="op">=</span><span class="dv">200</span>,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>    maxDepth<span class="op">=</span><span class="dv">6</span>,</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    seed<span class="op">=</span><span class="dv">42</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Model</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>rf_model <span class="op">=</span> rf.fit(train_rf)</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluation</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>rf_predictions <span class="op">=</span> rf_model.transform(test_rf)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>evaluator <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>)</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> evaluator.setMetricName(<span class="st">"r2"</span>).evaluate(rf_predictions)</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> evaluator.setMetricName(<span class="st">"rmse"</span>).evaluate(rf_predictions)</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>mae <span class="op">=</span> evaluator.setMetricName(<span class="st">"mae"</span>).evaluate(rf_predictions)</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Random Forest Results"</span>)</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"R²:"</span>, r2)</span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"RMSE:"</span>, rmse)</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MAE:"</span>, mae)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 85:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 86:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 87:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 89:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 91:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 93:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 95:&gt;                                                         (0 + 1) / 1]                                                                                25/10/08 03:30:43 WARN DAGScheduler: Broadcasting large task binary with size 1244.7 KiB
[Stage 97:&gt;                                                         (0 + 1) / 1]                                                                                25/10/08 03:30:45 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
[Stage 99:&gt;                                                         (0 + 1) / 1][Stage 100:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 101:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 102:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 103:&gt;                                                        (0 + 1) / 1]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest Results
R²: 0.9724973538145091
RMSE: 7022.572482052369
MAE: 4380.591032239985</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
</div>
<section id="feature-importance-plot" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="feature-importance-plot"><span class="header-section-number">7.1</span> Feature Importance Plot</h3>
<div id="8e669cc1" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># OHE vector size</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>ohe_sizes <span class="op">=</span> {c<span class="op">+</span><span class="st">"_OHE"</span>: df_transformed.select(c<span class="op">+</span><span class="st">"_OHE"</span>).head()[<span class="dv">0</span>].size <span class="cf">for</span> c <span class="kw">in</span> cat_cols}</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Expanded feature names</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>expanded_feature_names <span class="op">=</span> []</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> cont_cols:</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>    expanded_feature_names.append(col)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> cat_cols:</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(ohe_sizes[c<span class="op">+</span><span class="st">"_OHE"</span>]):</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>        expanded_feature_names.append(<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">}</span><span class="ss">_</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>importances <span class="op">=</span> rf_model.featureImportances.toArray()</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>feat_imp <span class="op">=</span> pd.DataFrame({</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"feature"</span>: expanded_feature_names,</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"importance"</span>: importances</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 10 plot</span></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>top10 <span class="op">=</span> feat_imp.sort_values(<span class="st">"importance"</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>)</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">6</span>))</span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a>sns.barplot(x<span class="op">=</span><span class="st">"importance"</span>, y<span class="op">=</span><span class="st">"feature"</span>, data<span class="op">=</span>top10, palette<span class="op">=</span><span class="st">"viridis"</span>)</span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Top 10 Feature Importances - Random Forest"</span>)</span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">"_output/rf_feature_importance.png"</span>)</span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_4414/192427344.py:28: FutureWarning:



Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment04-anush09_files/figure-html/cell-7-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="inference-2" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="inference-2"><span class="header-section-number">7.2</span> Inference</h3>
<p>The Random Forest model explained about 97% of salary variation (R² ≈ 0.97). But its errors were higher (RMSE ≈ 7023, MAE ≈ 4381) compared to linear models. From feature importance, we see that SALARY_TO and SALARY_FROM are the main drivers, with years of experience adding some effect. Other features like job type and state have very small impact. This means the model predicts well, but it mostly depends on salary range fields and gives less extra insight.</p>
</section>
</section>
<section id="model-comparison" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="model-comparison"><span class="header-section-number">8</span> Model Comparison</h2>
<div id="e58b2eae" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> RegressionEvaluator</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictions for all three models</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>lr_predictions <span class="op">=</span> lr_model.transform(test_df)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>poly_predictions <span class="op">=</span> lr_poly_model.transform(test_poly)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>rf_predictions <span class="op">=</span> rf_model.transform(test_rf)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>evaluator <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Regression metrics</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>lr_r2 <span class="op">=</span> evaluator.setMetricName(<span class="st">"r2"</span>).evaluate(lr_predictions)</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>lr_rmse <span class="op">=</span> evaluator.setMetricName(<span class="st">"rmse"</span>).evaluate(lr_predictions)</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>lr_mae <span class="op">=</span> evaluator.setMetricName(<span class="st">"mae"</span>).evaluate(lr_predictions)</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a><span class="co"># AIC for Linear Regression</span></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>lr_aic <span class="op">=</span> lr_model.summary.aic</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Linear Regression AIC: </span><span class="sc">{</span>lr_aic<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Polynomial Regression metrics</span></span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>poly_r2 <span class="op">=</span> evaluator.setMetricName(<span class="st">"r2"</span>).evaluate(poly_predictions)</span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>poly_rmse <span class="op">=</span> evaluator.setMetricName(<span class="st">"rmse"</span>).evaluate(poly_predictions)</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>poly_mae <span class="op">=</span> evaluator.setMetricName(<span class="st">"mae"</span>).evaluate(poly_predictions)</span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a><span class="co"># AIC for Polynomial Regression</span></span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>poly_aic <span class="op">=</span> lr_poly_model.summary.aic</span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Polynomial Regression AIC: </span><span class="sc">{</span>poly_aic<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a><span class="co"># AIC is not directly available for Random Forest</span></span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>rf_aic <span class="op">=</span> <span class="va">None</span></span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a><span class="co"># BIC calculation for Linear and Polynomial models</span></span>
<span id="cb35-34"><a href="#cb35-34" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_bic(model_summary, n_obs):</span>
<span id="cb35-35"><a href="#cb35-35" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Calculate BIC for PySpark GeneralizedLinearRegression models"""</span></span>
<span id="cb35-36"><a href="#cb35-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb35-37"><a href="#cb35-37" aria-hidden="true" tabindex="-1"></a>        k <span class="op">=</span> <span class="bu">len</span>(model_summary.coefficientStandardErrors) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb35-38"><a href="#cb35-38" aria-hidden="true" tabindex="-1"></a>        deviance <span class="op">=</span> model_summary.deviance</span>
<span id="cb35-39"><a href="#cb35-39" aria-hidden="true" tabindex="-1"></a>        dispersion <span class="op">=</span> model_summary.dispersion</span>
<span id="cb35-40"><a href="#cb35-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-41"><a href="#cb35-41" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Log Likelihood calculation</span></span>
<span id="cb35-42"><a href="#cb35-42" aria-hidden="true" tabindex="-1"></a>        log_likelihood <span class="op">=</span> <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> (n_obs <span class="op">*</span> np.log(<span class="dv">2</span> <span class="op">*</span> np.pi) <span class="op">+</span> n_obs <span class="op">*</span> np.log(dispersion) <span class="op">+</span> deviance<span class="op">/</span>dispersion)</span>
<span id="cb35-43"><a href="#cb35-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-44"><a href="#cb35-44" aria-hidden="true" tabindex="-1"></a>        <span class="co"># BIC calculation</span></span>
<span id="cb35-45"><a href="#cb35-45" aria-hidden="true" tabindex="-1"></a>        bic <span class="op">=</span> k <span class="op">*</span> np.log(n_obs) <span class="op">-</span> <span class="dv">2</span> <span class="op">*</span> log_likelihood</span>
<span id="cb35-46"><a href="#cb35-46" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> bic</span>
<span id="cb35-47"><a href="#cb35-47" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb35-48"><a href="#cb35-48" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"BIC calculation failed: </span><span class="sc">{</span><span class="bu">str</span>(e)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb35-49"><a href="#cb35-49" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb35-50"><a href="#cb35-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-51"><a href="#cb35-51" aria-hidden="true" tabindex="-1"></a>n_obs <span class="op">=</span> test_df.count()</span>
<span id="cb35-52"><a href="#cb35-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-53"><a href="#cb35-53" aria-hidden="true" tabindex="-1"></a>lr_bic <span class="op">=</span> calculate_bic(lr_model.summary, n_obs)</span>
<span id="cb35-54"><a href="#cb35-54" aria-hidden="true" tabindex="-1"></a>poly_bic <span class="op">=</span> calculate_bic(lr_poly_model.summary, n_obs)</span>
<span id="cb35-55"><a href="#cb35-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-56"><a href="#cb35-56" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Linear Regression BIC: </span><span class="sc">{</span>lr_bic<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb35-57"><a href="#cb35-57" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Polynomial Regression BIC: </span><span class="sc">{</span>poly_bic<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb35-58"><a href="#cb35-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-59"><a href="#cb35-59" aria-hidden="true" tabindex="-1"></a>comparison_data <span class="op">=</span> {</span>
<span id="cb35-60"><a href="#cb35-60" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Model'</span>: [<span class="st">'Generalized Linear Regression'</span>, <span class="st">'Polynomial Regression'</span>, <span class="st">'Random Forest'</span>],</span>
<span id="cb35-61"><a href="#cb35-61" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R²'</span>: [lr_r2, poly_r2, r2],</span>
<span id="cb35-62"><a href="#cb35-62" aria-hidden="true" tabindex="-1"></a>    <span class="st">'RMSE'</span>: [lr_rmse, poly_rmse, rmse],</span>
<span id="cb35-63"><a href="#cb35-63" aria-hidden="true" tabindex="-1"></a>    <span class="st">'MAE'</span>: [lr_mae, poly_mae, mae],</span>
<span id="cb35-64"><a href="#cb35-64" aria-hidden="true" tabindex="-1"></a>    <span class="st">'AIC'</span>: [lr_aic, poly_aic, <span class="st">'N/A'</span>],</span>
<span id="cb35-65"><a href="#cb35-65" aria-hidden="true" tabindex="-1"></a>    <span class="st">'BIC'</span>: [lr_bic, poly_bic, <span class="st">'N/A'</span>]</span>
<span id="cb35-66"><a href="#cb35-66" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-67"><a href="#cb35-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-68"><a href="#cb35-68" aria-hidden="true" tabindex="-1"></a>comparison_df <span class="op">=</span> pd.DataFrame(comparison_data)</span>
<span id="cb35-69"><a href="#cb35-69" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Model Comparison:"</span>)</span>
<span id="cb35-70"><a href="#cb35-70" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(comparison_df.to_string(index<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 106:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 107:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 108:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 109:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression AIC: 198674.9323303638</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 110:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 111:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 112:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 113:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Polynomial Regression AIC: 198675.85731451394</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 114:&gt;                                                        (0 + 1) / 1]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression BIC: 57339.69563876513
Polynomial Regression BIC: 57346.620360372595
Model Comparison:
                        Model       R²        RMSE         MAE            AIC           BIC
Generalized Linear Regression 0.999101 1269.832252  439.383598   198674.93233  57339.695639
        Polynomial Regression 0.999102 1269.217725  438.815563  198675.857315   57346.62036
                Random Forest 0.972497 7022.572482 4380.591032            N/A           N/A</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
</div>
<section id="visualization-comparison" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="visualization-comparison"><span class="header-section-number">8.1</span> Visualization Comparison</h3>
<div id="1166f645" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>lr_pd <span class="op">=</span> lr_predictions.select(<span class="st">"SALARY"</span>, <span class="st">"prediction"</span>).toPandas()</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>poly_pd <span class="op">=</span> poly_predictions.select(<span class="st">"SALARY"</span>, <span class="st">"prediction"</span>).toPandas()</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>rf_pd <span class="op">=</span> rf_predictions.select(<span class="st">"SALARY"</span>, <span class="st">"prediction"</span>).toPandas()</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">12</span>))</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Model Predictions vs Actual Values'</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Generalized Linear Regression</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].scatter(lr_pd[<span class="st">'SALARY'</span>], lr_pd[<span class="st">'prediction'</span>], alpha<span class="op">=</span><span class="fl">0.6</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].plot([lr_pd[<span class="st">'SALARY'</span>].<span class="bu">min</span>(), lr_pd[<span class="st">'SALARY'</span>].<span class="bu">max</span>()],</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>                [lr_pd[<span class="st">'SALARY'</span>].<span class="bu">min</span>(), lr_pd[<span class="st">'SALARY'</span>].<span class="bu">max</span>()], <span class="st">'r--'</span>, lw<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_xlabel(<span class="st">'Actual Salary'</span>)</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_ylabel(<span class="st">'Predicted Salary'</span>)</span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_title(<span class="ss">f'Linear Regression (R² = </span><span class="sc">{</span>lr_r2<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Polynomial Regression</span></span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].scatter(poly_pd[<span class="st">'SALARY'</span>], poly_pd[<span class="st">'prediction'</span>], alpha<span class="op">=</span><span class="fl">0.6</span>, color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].plot([poly_pd[<span class="st">'SALARY'</span>].<span class="bu">min</span>(), poly_pd[<span class="st">'SALARY'</span>].<span class="bu">max</span>()],</span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>                [poly_pd[<span class="st">'SALARY'</span>].<span class="bu">min</span>(), poly_pd[<span class="st">'SALARY'</span>].<span class="bu">max</span>()], <span class="st">'r--'</span>, lw<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_xlabel(<span class="st">'Actual Salary'</span>)</span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_ylabel(<span class="st">'Predicted Salary'</span>)</span>
<span id="cb43-26"><a href="#cb43-26" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_title(<span class="ss">f'Polynomial Regression (R² = </span><span class="sc">{</span>poly_r2<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb43-27"><a href="#cb43-27" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb43-28"><a href="#cb43-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-29"><a href="#cb43-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Random Forest</span></span>
<span id="cb43-30"><a href="#cb43-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].scatter(rf_pd[<span class="st">'SALARY'</span>], rf_pd[<span class="st">'prediction'</span>], alpha<span class="op">=</span><span class="fl">0.6</span>, color<span class="op">=</span><span class="st">'orange'</span>)</span>
<span id="cb43-31"><a href="#cb43-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].plot([rf_pd[<span class="st">'SALARY'</span>].<span class="bu">min</span>(), rf_pd[<span class="st">'SALARY'</span>].<span class="bu">max</span>()],</span>
<span id="cb43-32"><a href="#cb43-32" aria-hidden="true" tabindex="-1"></a>                [rf_pd[<span class="st">'SALARY'</span>].<span class="bu">min</span>(), rf_pd[<span class="st">'SALARY'</span>].<span class="bu">max</span>()], <span class="st">'r--'</span>, lw<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb43-33"><a href="#cb43-33" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_xlabel(<span class="st">'Actual Salary'</span>)</span>
<span id="cb43-34"><a href="#cb43-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_ylabel(<span class="st">'Predicted Salary'</span>)</span>
<span id="cb43-35"><a href="#cb43-35" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_title(<span class="ss">f'Random Forest (R² = </span><span class="sc">{</span>r2<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb43-36"><a href="#cb43-36" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb43-37"><a href="#cb43-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-38"><a href="#cb43-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Model comparison bar chart using Seaborn</span></span>
<span id="cb43-39"><a href="#cb43-39" aria-hidden="true" tabindex="-1"></a>model_names <span class="op">=</span> [<span class="st">'Linear'</span>, <span class="st">'Polynomial'</span>, <span class="st">'Random Forest'</span>]</span>
<span id="cb43-40"><a href="#cb43-40" aria-hidden="true" tabindex="-1"></a>r2_scores <span class="op">=</span> [lr_r2, poly_r2, r2]</span>
<span id="cb43-41"><a href="#cb43-41" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'blue'</span>, <span class="st">'green'</span>, <span class="st">'orange'</span>]</span>
<span id="cb43-42"><a href="#cb43-42" aria-hidden="true" tabindex="-1"></a>comparison_plot_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb43-43"><a href="#cb43-43" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Model'</span>: model_names,</span>
<span id="cb43-44"><a href="#cb43-44" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R²'</span>: r2_scores</span>
<span id="cb43-45"><a href="#cb43-45" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb43-46"><a href="#cb43-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-47"><a href="#cb43-47" aria-hidden="true" tabindex="-1"></a>sns.barplot(data<span class="op">=</span>comparison_plot_df, x<span class="op">=</span><span class="st">'R²'</span>, y<span class="op">=</span><span class="st">'Model'</span>, palette<span class="op">=</span>colors, ax<span class="op">=</span>axes[<span class="dv">1</span>, <span class="dv">1</span>])</span>
<span id="cb43-48"><a href="#cb43-48" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].set_xlabel(<span class="st">'R² Score'</span>)</span>
<span id="cb43-49"><a href="#cb43-49" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].set_title(<span class="st">'Model Performance Comparison (R²)'</span>)</span>
<span id="cb43-50"><a href="#cb43-50" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb43-51"><a href="#cb43-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-52"><a href="#cb43-52" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb43-53"><a href="#cb43-53" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">"_output/model_comparison.png"</span>, dpi<span class="op">=</span><span class="dv">300</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb43-54"><a href="#cb43-54" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb43-55"><a href="#cb43-55" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 117:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 118:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 119:&gt;                                                        (0 + 1) / 1]                                                                                /tmp/ipykernel_4414/3842274766.py:47: FutureWarning:



Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment04-anush09_files/figure-html/cell-9-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="inference-3" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="inference-3"><span class="header-section-number">8.2</span> Inference</h3>
<p>Both the Generalized Linear Regression and Polynomial Regression models performed almost identically, with R² ≈ 0.9991 and very low errors (RMSE ≈ 1269, MAE ≈ 439). Their AIC and BIC values are also very close, showing no real advantage of adding polynomial terms. The Random Forest model explained less variation (R² ≈ 0.97) and had much higher errors (RMSE ≈ 7023, MAE ≈ 4381). Since AIC and BIC are not available for Random Forest, comparison is based only on accuracy metrics. Overall, the linear models clearly outperform Random Forest for this dataset. Between them, the simpler Generalized Linear Regression is preferable, as it achieves the same accuracy with lower complexity and easier interpretation.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>